### ISSUE TITLE
conflicts with DIVI builder 

### ISSUE THREAD

**Issue by jtbayly** [MediaRon/highlight-and-share#21]
When attempting to use this plugin with DIVI builder in Extra Theme (from Elegant Themes) the builder is unusable. Anytime I click on a block to pull up its settings or duplicate it or anything else (whether in the front-end visual editor or in the backend editor) it starts me dragging and dropping the block, and it becomes impossible to click to put the block back in place.

It seems odd to me that this even happens in the backend, but I thought you'd want to know so you can look into fixing it.

**Comment by ronalfy** [comment]
@jtbayly is there a way you can share your setup with me? I don't have Divi of the Extra theme. Perhaps a staging site I can have access to?

**Comment by jtbayly** [comment]
Yes. I can do that. How should I send you private info?

**Comment by joshsloat** [comment]
@ronalfy @jtbayly Any updates on this one? I'm running into the exact same problem. Anything that should be selectable in the builder (markers to add rows, sections, modules, etc) become undocked and start moving around with your mouse.

**Comment by jtbayly** [comment]
For a while I disabled it while editing in the backend. Then I just permanently disabled it.

**Comment by joshsloat** [comment]
I ended up using [Epic Sharer](https://wordpress.org/plugins/epic-selection-sharer/) instead, but it’s not nearly as feature rich.

**Comment by ronalfy** [comment]
I've discovered the same thing with Beaver Builder. Something to do with the mouseup JavaScript action. I haven't found a fix yet.

**Comment by joshsloat** [comment]
Roger that. Thanks for the update @ronalfy and for all of your work on this plugin.

**Comment by ronalfy** [comment]
It's been a bit, but this has been resolved.
