### ISSUE TITLE
Conflict with Elementor

### ISSUE THREAD

**Issue by Shinny1** [MediaRon/highlight-and-share#26]
Hello Roland,

First I want to thank you for this great plugin. You really did a nice job. It is really awesome.

It appears that between the plugin and Elementor it is a bit of a conflict. I have the latest versions for both your plugin and Elementor.

My issue is the following. 

If I set a link color in the Global Theme Style Kits from Elementor, that color seems to also affect the share icons from your plugin. For each theme I select from your plugin, my global link color that I customized only for the text it appears also on the share icons.

I don't want that. What I configure in Elementor should not have any affect on what I configure in your plugin options.

I want to use the theme Black Icons Only. It should display my share icons only in black and white even if I hover on them or not.

In my case the icons use the link color configured from Elementor, and only when I hover on the icons is looks ok with black and white.

![color problem](https://user-images.githubusercontent.com/20139737/81257147-3aab5a80-903b-11ea-8ce9-2ec74d1e048f.PNG)

Can you do something about this conflict?

Thanks

**Comment by ronalfy** [comment]
@Shinny1 are you using the pro version of elementor or using this plugin at all? https://wordpress.org/plugins/analogwp-templates/

Trying to reproduce.

Thanks,

Ronald

**Comment by Shinny1** [comment]
Hello,
I am using Elementor Pro.  Two months ago the Elementor team added style kits to their plugin.
Thanks.

**Comment by ronalfy** [comment]
@Shinny1 

I just released version 3.2.11, which fixes the styles in my tests with Elementor Pro. 

Thanks for bringing it to my attention.

https://wordpress.org/plugins/highlight-and-share/#developers

Regards,

Ronald Huereca
